# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_bd_ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1000, 537)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 537))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 537))
        MainWindow.setBaseSize(QtCore.QSize(1100, 660))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/icon_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 500))
        self.centralwidget.setBaseSize(QtCore.QSize(1000, 500))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 991, 491))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid_main_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid_main_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.grid_main_layout.setContentsMargins(5, 5, 5, 5)
        self.grid_main_layout.setObjectName("grid_main_layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.form_layout_fio = QtWidgets.QFormLayout()
        self.form_layout_fio.setContentsMargins(5, 5, 5, 5)
        self.form_layout_fio.setObjectName("form_layout_fio")
        self.label_family = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_family.sizePolicy().hasHeightForWidth())
        self.label_family.setSizePolicy(sizePolicy)
        self.label_family.setMinimumSize(QtCore.QSize(50, 0))
        self.label_family.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_family.setScaledContents(False)
        self.label_family.setObjectName("label_family")
        self.form_layout_fio.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_family)
        self.edit_family = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_family.sizePolicy().hasHeightForWidth())
        self.edit_family.setSizePolicy(sizePolicy)
        self.edit_family.setText("")
        self.edit_family.setObjectName("edit_family")
        self.form_layout_fio.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_family)
        self.label_name = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        self.label_name.setMinimumSize(QtCore.QSize(50, 0))
        self.label_name.setObjectName("label_name")
        self.form_layout_fio.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.edit_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_name.sizePolicy().hasHeightForWidth())
        self.edit_name.setSizePolicy(sizePolicy)
        self.edit_name.setText("")
        self.edit_name.setObjectName("edit_name")
        self.form_layout_fio.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_name)
        self.label_farther = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_farther.sizePolicy().hasHeightForWidth())
        self.label_farther.setSizePolicy(sizePolicy)
        self.label_farther.setMinimumSize(QtCore.QSize(50, 0))
        self.label_farther.setObjectName("label_farther")
        self.form_layout_fio.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_farther)
        self.edit_farther = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_farther.sizePolicy().hasHeightForWidth())
        self.edit_farther.setSizePolicy(sizePolicy)
        self.edit_farther.setText("")
        self.edit_farther.setObjectName("edit_farther")
        self.form_layout_fio.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_farther)
        self.horizontalLayout.addLayout(self.form_layout_fio)
        self.form_layout_birthday = QtWidgets.QFormLayout()
        self.form_layout_birthday.setContentsMargins(5, 5, 5, 5)
        self.form_layout_birthday.setObjectName("form_layout_birthday")
        self.label_birthday_year = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_birthday_year.sizePolicy().hasHeightForWidth())
        self.label_birthday_year.setSizePolicy(sizePolicy)
        self.label_birthday_year.setMinimumSize(QtCore.QSize(90, 0))
        self.label_birthday_year.setObjectName("label_birthday_year")
        self.form_layout_birthday.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_birthday_year)
        self.edit_birthday_year = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_birthday_year.sizePolicy().hasHeightForWidth())
        self.edit_birthday_year.setSizePolicy(sizePolicy)
        self.edit_birthday_year.setText("")
        self.edit_birthday_year.setObjectName("edit_birthday_year")
        self.form_layout_birthday.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_birthday_year)
        self.label_birthday_month = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_birthday_month.sizePolicy().hasHeightForWidth())
        self.label_birthday_month.setSizePolicy(sizePolicy)
        self.label_birthday_month.setMinimumSize(QtCore.QSize(90, 0))
        self.label_birthday_month.setObjectName("label_birthday_month")
        self.form_layout_birthday.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_birthday_month)
        self.edit_birthday_month = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_birthday_month.sizePolicy().hasHeightForWidth())
        self.edit_birthday_month.setSizePolicy(sizePolicy)
        self.edit_birthday_month.setText("")
        self.edit_birthday_month.setObjectName("edit_birthday_month")
        self.form_layout_birthday.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_birthday_month)
        self.label_birthday_day = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_birthday_day.sizePolicy().hasHeightForWidth())
        self.label_birthday_day.setSizePolicy(sizePolicy)
        self.label_birthday_day.setMinimumSize(QtCore.QSize(90, 0))
        self.label_birthday_day.setObjectName("label_birthday_day")
        self.form_layout_birthday.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_birthday_day)
        self.edit_birthday_day = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_birthday_day.sizePolicy().hasHeightForWidth())
        self.edit_birthday_day.setSizePolicy(sizePolicy)
        self.edit_birthday_day.setText("")
        self.edit_birthday_day.setObjectName("edit_birthday_day")
        self.form_layout_birthday.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_birthday_day)
        self.horizontalLayout.addLayout(self.form_layout_birthday)
        self.vertical_layout_addons = QtWidgets.QVBoxLayout()
        self.vertical_layout_addons.setObjectName("vertical_layout_addons")
        self.horizontal_layout_zodiak = QtWidgets.QHBoxLayout()
        self.horizontal_layout_zodiak.setContentsMargins(5, 3, 5, 0)
        self.horizontal_layout_zodiak.setObjectName("horizontal_layout_zodiak")
        self.label_zodiak = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_zodiak.sizePolicy().hasHeightForWidth())
        self.label_zodiak.setSizePolicy(sizePolicy)
        self.label_zodiak.setMinimumSize(QtCore.QSize(40, 0))
        self.label_zodiak.setObjectName("label_zodiak")
        self.horizontal_layout_zodiak.addWidget(self.label_zodiak)
        self.combobox_zodiak = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.combobox_zodiak.setCurrentText("")
        self.combobox_zodiak.setObjectName("combobox_zodiak")
        self.horizontal_layout_zodiak.addWidget(self.combobox_zodiak)
        self.vertical_layout_addons.addLayout(self.horizontal_layout_zodiak)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.check_box_interactive = QtWidgets.QCheckBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_box_interactive.sizePolicy().hasHeightForWidth())
        self.check_box_interactive.setSizePolicy(sizePolicy)
        self.check_box_interactive.setChecked(False)
        self.check_box_interactive.setObjectName("check_box_interactive")
        self.horizontalLayout_2.addWidget(self.check_box_interactive)
        self.vertical_layout_addons.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.push_button_clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_button_clear.sizePolicy().hasHeightForWidth())
        self.push_button_clear.setSizePolicy(sizePolicy)
        self.push_button_clear.setObjectName("push_button_clear")
        self.horizontalLayout_3.addWidget(self.push_button_clear)
        self.push_button_search = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_button_search.sizePolicy().hasHeightForWidth())
        self.push_button_search.setSizePolicy(sizePolicy)
        self.push_button_search.setObjectName("push_button_search")
        self.horizontalLayout_3.addWidget(self.push_button_search)
        self.vertical_layout_addons.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.vertical_layout_addons)
        self.form_layout_city = QtWidgets.QFormLayout()
        self.form_layout_city.setContentsMargins(5, 5, 5, 5)
        self.form_layout_city.setObjectName("form_layout_city")
        self.label_city = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_city.sizePolicy().hasHeightForWidth())
        self.label_city.setSizePolicy(sizePolicy)
        self.label_city.setMinimumSize(QtCore.QSize(60, 0))
        self.label_city.setObjectName("label_city")
        self.form_layout_city.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_city)
        self.edit_city = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_city.sizePolicy().hasHeightForWidth())
        self.edit_city.setSizePolicy(sizePolicy)
        self.edit_city.setText("")
        self.edit_city.setObjectName("edit_city")
        self.form_layout_city.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_city)
        self.label_selsovet = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_selsovet.sizePolicy().hasHeightForWidth())
        self.label_selsovet.setSizePolicy(sizePolicy)
        self.label_selsovet.setMinimumSize(QtCore.QSize(60, 0))
        self.label_selsovet.setObjectName("label_selsovet")
        self.form_layout_city.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_selsovet)
        self.edit_selsovet = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_selsovet.sizePolicy().hasHeightForWidth())
        self.edit_selsovet.setSizePolicy(sizePolicy)
        self.edit_selsovet.setText("")
        self.edit_selsovet.setObjectName("edit_selsovet")
        self.form_layout_city.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_selsovet)
        self.label_ksiva = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ksiva.sizePolicy().hasHeightForWidth())
        self.label_ksiva.setSizePolicy(sizePolicy)
        self.label_ksiva.setMinimumSize(QtCore.QSize(60, 0))
        self.label_ksiva.setObjectName("label_ksiva")
        self.form_layout_city.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_ksiva)
        self.edit_ksiva = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_ksiva.sizePolicy().hasHeightForWidth())
        self.edit_ksiva.setSizePolicy(sizePolicy)
        self.edit_ksiva.setText("")
        self.edit_ksiva.setObjectName("edit_ksiva")
        self.form_layout_city.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_ksiva)
        self.horizontalLayout.addLayout(self.form_layout_city)
        self.form_layout_address = QtWidgets.QFormLayout()
        self.form_layout_address.setContentsMargins(5, 5, 5, 5)
        self.form_layout_address.setObjectName("form_layout_address")
        self.label_street = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_street.sizePolicy().hasHeightForWidth())
        self.label_street.setSizePolicy(sizePolicy)
        self.label_street.setMinimumSize(QtCore.QSize(50, 0))
        self.label_street.setObjectName("label_street")
        self.form_layout_address.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_street)
        self.edit_street = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_street.sizePolicy().hasHeightForWidth())
        self.edit_street.setSizePolicy(sizePolicy)
        self.edit_street.setText("")
        self.edit_street.setObjectName("edit_street")
        self.form_layout_address.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_street)
        self.label_house = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_house.sizePolicy().hasHeightForWidth())
        self.label_house.setSizePolicy(sizePolicy)
        self.label_house.setMinimumSize(QtCore.QSize(50, 0))
        self.label_house.setObjectName("label_house")
        self.form_layout_address.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_house)
        self.edit_house = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_house.sizePolicy().hasHeightForWidth())
        self.edit_house.setSizePolicy(sizePolicy)
        self.edit_house.setText("")
        self.edit_house.setObjectName("edit_house")
        self.form_layout_address.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_house)
        self.label_flat = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_flat.sizePolicy().hasHeightForWidth())
        self.label_flat.setSizePolicy(sizePolicy)
        self.label_flat.setMinimumSize(QtCore.QSize(50, 0))
        self.label_flat.setObjectName("label_flat")
        self.form_layout_address.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_flat)
        self.edit_flat = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_flat.sizePolicy().hasHeightForWidth())
        self.edit_flat.setSizePolicy(sizePolicy)
        self.edit_flat.setText("")
        self.edit_flat.setObjectName("edit_flat")
        self.form_layout_address.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_flat)
        self.horizontalLayout.addLayout(self.form_layout_address)
        self.horizontalLayout.setStretch(2, 1)
        self.grid_main_layout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.table_view_bd = QtWidgets.QTableView(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_view_bd.sizePolicy().hasHeightForWidth())
        self.table_view_bd.setSizePolicy(sizePolicy)
        self.table_view_bd.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.table_view_bd.setMidLineWidth(0)
        self.table_view_bd.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_view_bd.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_view_bd.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_view_bd.setSortingEnabled(True)
        self.table_view_bd.setObjectName("table_view_bd")
        self.grid_main_layout.addWidget(self.table_view_bd, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionReset)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BD"))
        self.label_family.setText(_translate("MainWindow", "Фамилия"))
        self.edit_family.setPlaceholderText(_translate("MainWindow", "Фамилия"))
        self.label_name.setText(_translate("MainWindow", "Имя"))
        self.edit_name.setPlaceholderText(_translate("MainWindow", "Имя"))
        self.label_farther.setText(_translate("MainWindow", "Отчество"))
        self.edit_farther.setPlaceholderText(_translate("MainWindow", "Отчество"))
        self.label_birthday_year.setText(_translate("MainWindow", "Рождения год"))
        self.edit_birthday_year.setPlaceholderText(_translate("MainWindow", "Рождения год"))
        self.label_birthday_month.setText(_translate("MainWindow", "Рождения месяц"))
        self.edit_birthday_month.setPlaceholderText(_translate("MainWindow", "Рождения месяц"))
        self.label_birthday_day.setText(_translate("MainWindow", "Рождения день"))
        self.edit_birthday_day.setPlaceholderText(_translate("MainWindow", "Рождения день"))
        self.label_zodiak.setText(_translate("MainWindow", "Зодиак"))
        self.check_box_interactive.setText(_translate("MainWindow", "Интерактивный поиск"))
        self.push_button_clear.setText(_translate("MainWindow", "Очистка"))
        self.push_button_search.setText(_translate("MainWindow", "Поиск"))
        self.label_city.setText(_translate("MainWindow", "Город"))
        self.edit_city.setPlaceholderText(_translate("MainWindow", "Город"))
        self.label_selsovet.setText(_translate("MainWindow", "Сельсовет"))
        self.edit_selsovet.setPlaceholderText(_translate("MainWindow", "Сельсовет"))
        self.label_ksiva.setText(_translate("MainWindow", "Документ"))
        self.edit_ksiva.setPlaceholderText(_translate("MainWindow", "Документ"))
        self.label_street.setText(_translate("MainWindow", "Улица"))
        self.edit_street.setPlaceholderText(_translate("MainWindow", "Улица"))
        self.label_house.setText(_translate("MainWindow", "Дом"))
        self.edit_house.setPlaceholderText(_translate("MainWindow", "Дом"))
        self.label_flat.setText(_translate("MainWindow", "Квартира"))
        self.edit_flat.setPlaceholderText(_translate("MainWindow", "Квартира"))
        self.menuFile.setTitle(_translate("MainWindow", "Файл"))
        self.menuHelp.setTitle(_translate("MainWindow", "Справка"))
        self.actionReset.setText(_translate("MainWindow", "Очистка"))
        self.actionExit.setText(_translate("MainWindow", "Выход"))
        self.actionAbout.setText(_translate("MainWindow", "О DB"))

